### ISSUE TITLE
 error: ‘ros’ has not been declared

### ISSUE THREAD

**Issue by lucasw** [dkargin/miniroscpp#6]
I put together https://github.com/lucasw/miniroscpp_demo/tree/basic_demo but I'm missing where to get `ros::` from

```

/home/runner/work/miniroscpp_demo/miniroscpp_demo/src/main.cpp: In function ‘int main(int, char**)’:
/home/runner/work/miniroscpp_demo/miniroscpp_demo/src/main.cpp:37:3: error: ‘ros’ has not been declared
   37 |   ros::init(argc, argv, "miniroscpp_demo");
      |   ^~~
/home/runner/work/miniroscpp_demo/miniroscpp_demo/src/main.cpp:39:3: error: ‘ros’ has not been declared
   39 |   ros::NodeHandle nh;
      |   ^~~
/home/runner/work/miniroscpp_demo/miniroscpp_demo/src/main.cpp:41:3: error: ‘ros’ has not been declared
   41 |   ros::Publisher image_pub = nh.advertise<sensor_msgs::Image>("image", 10);
      |   ^~~
/home/runner/work/miniroscpp_demo/miniroscpp_demo/src/main.cpp:43:3: error: ‘ros’ has not been declared
   43 |   ros::Rate loop_rate(3);
      |   ^~~
/home/runner/work/miniroscpp_demo/miniroscpp_demo/src/main.cpp:58:10: error: ‘ros’ has not been declared
   58 |   while (ros::ok()) {
      |          ^~~
/home/runner/work/miniroscpp_demo/miniroscpp_demo/src/main.cpp:60:24: error: ‘ros’ has not been declared
   60 |     msg.header.stamp = ros::Time::now();
      |                        ^~~```
```

https://github.com/lucasw/miniroscpp_demo/runs/2814239111?check_suite_focus=true

https://github.com/lucasw/miniroscpp_demo/blob/basic_demo/.github/workflows/ubuntu_20_04.yml

I see it getting used in the examples (which I can't yet build, I can only build the main library, that could be another issue), but I don't see it in the source code.

**Comment by dkargin** [comment]
There is still no transport stuff done yet. So no NodeHandler/Publisher/Subscriber. The only things done is general serialization and rosbag API.

For now the only relevant examples are [bag_read.cpp](https://github.com/dkargin/miniroscpp/blob/master/examples/bag_read.cpp) and [bag_write.cpp](https://github.com/dkargin/miniroscpp/blob/master/examples/bag_write.cpp)

**Comment by dkargin** [comment]
Since this issue is not directly related to `miniros`, I am closing it

**Comment by dkargin** [comment]
@lucasw Transport is complete and usable now. There are 1:1 replacements for original NodeHander/Publisher/Subscriber now. Just replace ros->miniros
